"""empty message

Revision ID: 507593124732
Revises: c61126698859
Create Date: 2023-12-02 20:40:04.400609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507593124732'
down_revision = 'c61126698859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###
